services:
  jenkins:
    build:
      context: .
      args:
        AWS_ACCESS_KEY_ID: "{your_aws_access_key_id}"
        AWS_SECRET_ACCESS_KEY: "{your_aws_secret_access_key}"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - C:/jenkins_home_softserve:/var/jenkins_home

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "http://jenkins:8080"
    environment:
      - NGROK_AUTHTOKEN=2qRx3YPoWDroiH321kOqKwEEGfW_2CZAW92yPN7QhqZWZbmvf
    ports:
      - "4040:4040"


