- name: Config infrastucture webapp
  hosts: webservers
  become: yes
  vars:
    app_dir: /opt/flaskapp
    
  tasks:
    - name: Install dependecies for system
      package:
        name:
          - git
          - python3
          - python3-pip
          - gcc
        state: present

    - name: Install Gunicorn
      pip:
        name:
          - gunicorn
        state: present
        
    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'